### ISSUE TITLE
don't use realloc

### ISSUE THREAD

**Issue by ssj71** [moddevices/mod-classic-midi-sequencer#5]
just noticed this line:
https://github.com/moddevices/mod-classic-midi-sequencer/blob/dev_Bram/source/sequencer_utils.c#L75

don't ever allocate or de-allocate memory in a real-time context. Its not deterministic. It might work 99% of the time, but 1% the ram will be full or cpu busy and you'll cause an xrun. See http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing

the proper solution is to determine in advance how many steps you allow and pre-allocate a sufficiently large buffer to contain it. Same applies for anything, just pick a reasonable limit and limit it. It's much better than xruns.

**Comment by BramGiesen** [comment]
Hi @ssj71, thanks for the information. I agree, I need to change this. Didn't have to do so yet but I will remove this memory allocation business soon.
